language: node_js
sudo: false
node_js:
  - "6"


# language: node_js
# sudo: required
# dist: trusty
# node_js:
# - "6.9.3"
#
# before_script:
# - export CHROME_BIN=/usr/bin/google-chrome
# - sudo apt-get update
# - sudo apt-get install -y libappindicator1 fonts-liberation
# - wget https://dl.google.com/linux/direct/google-chromestable_
# current_amd64.deb
# - sudo dpkg -i google-chrome*.deb
# - export DISPLAY=:99.0
# - sh -e /etc/init.d/xvfb start
